#!/bin/bash
# Program to output a system information page

#echo "<HTML>"
#echo "  <head>"
#echo "      <title> Page Title </title>"
#echo "  </head>"
#echo "  <body>"
#echo "      Page body"
#echo "  </body>"
#echo "</HTML>"

title = "System Information Report"

echo "
<html>
    <head>
        <title>$title</title>
    </head>
    <body>
        <h1>$title</h1>
    </body>
</html>
"
